name: "Get Changed Files"

on: 
  push:
    branches:
      - master

jobs:
  changedFiles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get changed files
        id: changes
        run: |
          echo 
          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
          echo "::set-output name=ts::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .ts$ | xargs)"
      - name: Echo changed files
        run: echo ${{ steps.changes.outputs.all }}
      - name: echo changed files
        run: echo "${{ github.event.pull_request.base.sha }} ${{ github.sha }}"
      