name: "Check file for console.log and console.error"

on: 
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
    
jobs:
  find_occurences:
    name: Find occurences of console.log|console.error
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Show GitHub context TEST
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Find occurences 
        uses: ./
        id: changed-files
        with:
          before-sha: ${{ github.event.before }}
          after-sha: ${{ github.sha }}
          search-term: console.log|console.error
          file-types: (.ts|.js|.tsx|.jsx)$
          should-fail: true
        