name: "Get Changed Files"

on: 
  push:
    branches:
      - master

jobs:
  changedFiles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  my_action:
    needs: changedFiles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Action 
        uses: ./
        id: changed-files
        with:
          before-sha: ${{ github.event.before }}
          after-sha: ${{ github.sha }}

      - name: All changed files
        run: echo "${{ steps.changed-files.outputs.all }}"

      - name: All changed files (typescript)
        run: echo "${{ steps.changed-files.outputs.ts }}"
      