name: "Get Changed Files"

on: 
  push:
    branches:
      - master

jobs:
  changedFiles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get changed files
        id: changes
        run: |
          echo 
          echo "::set-output name=all::$()"
          echo "::set-output name=ts::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.before }} ${{ github.sha }} | grep .ts$ | xargs)"
      - name: Echo changed files
        run: echo ${{ steps.changes.outputs.all }}
      - name: echo changed files
        run: echo "${{ github.event.before }} ${{ github.sha }}"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  my_action:
    needs: changedFiles
    runs-on: ubuntu-latest
    steps:
      - name: Action 
        uses: ./
        id: check-files
      - name: Echo ls
        run: echo ${{ steps.check-files.outputs.ls }}
      